import { useState, useEffect } from "react";
import Head from "next/head";
//import Image from "next/image";
//import styles from "../styles/Home.module.css";
import SushiSection from "../components/SushiSection";
import Top from "../components/Top";

export default function Home() {
  const [offsetY, setOffsetY] = useState(0);
  const handleScroll = () => setOffsetY(window.scrollY);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => window.removeEventListener("scroll", handleScroll);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Top />
      <SushiSection />
      <SushiSection />
      <SushiSection />
    </>
  );
}
