//import { useEffect, useState } from "react";
import Head from "next/head";
import Top from "../components/Top";
import Boxes from "../components/Boxes";
import Spacer from "../components/Spacer";
import Footer from "../components/Footer";
import NameSpacer from "../components/NameSpacer";
import BeefBroccoli from "../components/BeefBrocoli";
import SushiSection from "../components/SushiSection";

export default function Home() {
  /* const [offsetY, setOffsetY] = useState(0);
  const handleScroll = () => setOffsetY(window.scrollY); */

  /* useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => window.removeEventListener("scroll", handleScroll);
  }, []); */
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Top />
      <NameSpacer />
      <Boxes />
      <BeefBroccoli />
      <Spacer />
      <SushiSection />
      <Footer />
    </>
  );
}
