import { useEffect, useState } from "react";
import Head from "next/head";
//import Image from "next/image";
//import styles from "../styles/Home.module.css";
import SushiSection from "../components/SushiSection";
import Top from "../components/Top";
import Boxes from "../components/Boxes";
import Spacer from "../components/Spacer";
//import FoodSection from "../components/FoodSection";
import BeefBroccoli from "../components/BeefBrocoli";
import NameSpacer from "../components/NameSpacer";

export default function Home() {
  const [offsetY, setOffsetY] = useState(0);
  const handleScroll = () => setOffsetY(window.scrollY);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => window.removeEventListener("scroll", handleScroll);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Top />
      <NameSpacer />
      <Boxes />
      {/* <FoodSection /> */}
      <BeefBroccoli />
      <Spacer />
      <SushiSection />
    </>
  );
}
